### ISSUE TITLE
input valid pixels boundaries error

### ISSUE THREAD

**Issue by zulkifil** [lmotta/ibamaprocessing#2]
I mostly used it to create input valid pixels boundaries. It was working great and creating boundaries but now it is not creating input valid pixels boundaries from raster's and mostly give error. it only create bounding box boundaries. I think previously it was also catering alpha band and now it is not using alpha band and looking for nodata value 0. below is error i receive all the time.

`QGIS version: 3.16.5-Hannover
QGIS code revision: 58ba7c1ed6
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Create footprint of images' starting…
Input parameters:
{ 'INPUT_CRS_AREA' : QgsCoordinateReferenceSystem('EPSG:32643'), 'INPUT_CRS_LAYER' : QgsCoordinateReferenceSystem('EPSG:32643'), 'INPUT_DIRECTORY_IMAGES' : 'D:\\rabM\\Isl\\d\\E\\New folder', 'INPUT_FILTER_NAMES' : '', 'INPUT_NODATA' : 0, 'INPUT_REVERSE' : False, 'INPUT_SUBDIRECTORIES' : False, 'INPUT_VALID_PIXELS' : 1, 'OUTPUT_LAYER' : 'TEMPORARY_OUTPUT' }

1/2 Searching images...
2/2 Adding features(3)...
Traceback (most recent call last):
File "C:/Users/AA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ibamaprocessing\algorithms\footprint_algorithm.py", line 700, in processAlgorithm
footprint.setGeometryArea( crsLayer, crsArea, paramsValidPixels )
File "C:/Users/AA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ibamaprocessing\algorithms\footprint_algorithm.py", line 486, in setGeometryArea
setGeometryInfo( info )
File "C:/Users/AA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ibamaprocessing\algorithms\footprint_algorithm.py", line 453, in setGeometryValidPixels
geomUnion.AddGeometry( geomsOGR[ idx ] )
IndexError: list index out of range

Execution failed after 9.33 seconds

Loading resulting layers
Algorithm 'Create footprint of images' finished`

**Comment by lmotta** [comment]
Hi,

The algorithm takes the first band, if this has the nodata value(defined in
file), this value is used for calculus, otherwise, take the value in the
textbox.

Please, can you share an image where there is an error?

Em seg., 29 de mar. de 2021 às 15:32, AMZ ***@***.***>
escreveu:

**Comment by nmromeros** [comment]
Hi @lmotta , I have the same error like the comment of @zulkifil, this is the error that I get. I hope you can help me.

I have the version of qgis 3.16.16-Hannover

QGIS code revision f5778a89
Compiled against Qt 5.15.2
Running against Qt 5.15.2
Compiled against GDAL/OGR 3.4.1
Running against GDAL/OGR 3.4.1
Compiled against GEOS 3.10.0-CAPI-1.16.0
Running against GEOS 3.10.0-CAPI-1.16.0
Compiled against SQLite 3.35.2
Running against SQLite 3.35.2
PostgreSQL Client Version 13.0
SpatiaLite Version 5.0.1
QWT Version 6.1.3
QScintilla2 Version 2.11.5
Compiled against PROJ 8.2.1
Running against PROJ Rel. 8.2.1, January 1st, 2022 
OS Version Windows Server 2016 Version 1809
Active python plugins ibamaprocessing; db_manager;  MetaSearch;  processing

I load the image that present the error.

Thanks a lot

![Error ibama](https://user-images.githubusercontent.com/100386407/155749705-64da0ce3-2a94-44fc-83d4-e64eeebb6e4f.jpg)

**Comment by zulkifil** [comment]
@nmromeros do not use latest version, use older version to solve problem.

**Comment by nmromeros** [comment]
Hi @zulkifil what version do you recommend.?


what version do you have?

Thanks a lot.

**Comment by zulkifil** [comment]
@nmromeros use 1.5 version.
